# Generated by Django 3.0.8 on 2020-07-28 19:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_name', models.CharField(max_length=30)),
                ('guide_body', models.TextField(max_length=2000)),
                ('hero', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(119), django.core.validators.MinValueValidator(1)])),
                ('published', models.BooleanField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_description', models.CharField(max_length=250)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='guides.Guide')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_name', models.CharField(max_length=50)),
                ('attribute', models.CharField(max_length=12)),
                ('attack_type', models.CharField(max_length=6)),
                ('roles', models.ManyToManyField(to='guides.Role')),
            ],
        ),
    ]
